services:
  mosters:
    build:
      context: ./mosters
      dockerfile: Dockerfile
    volumes:
      - ./posters:/app/posters
    ports:
      - 8080:8080
    environment:
      - POSTER_DIR=/posters
  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - localprom
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana:7.5.7
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./grafana/:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana
      
volumes:
  grafana-data:
networks:
  localprom:
    driver: bridge